export const ROUTES = Object.freeze({
  HOME: "/", ABOUT: "/about", CONTACT: "/contact", GALLERY: "/gallery", BLOG: "/blog",
  LOGIN: "/login", REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password", ONBOARDING: "/onboarding",
  ADMIN: "/admin",
  ADMIN_FEES: "/admin/fees",
  ADMIN_FEES_STRUCTURE: "/admin/fees/structure",
  ADMIN_FEES_INVOICES: "/admin/fees/invoices",
  ADMIN_FEES_PAYMENTS: "/admin/fees/payments",
  STUDENT: "/student",
  STUDENT_FEES: "/student/fees",
  PARENT: "/parent",
  PARENT_CHILD_FEES: "/parent/child-fees",
  TEACHER: "/teacher",
  SUPER_ADMIN: "/super-admin",
});
